/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Integrador;

/**
 *
 * @author Faith
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Conexion = new javax.swing.JDialog();
        jd_Integracion = new javax.swing.JDialog();
        lbl_Titulo = new javax.swing.JLabel();
        mb_Menu = new javax.swing.JMenuBar();
        mi_Integrador = new javax.swing.JMenu();
        mi_Salida = new javax.swing.JMenu();

        javax.swing.GroupLayout jd_ConexionLayout = new javax.swing.GroupLayout(jd_Conexion.getContentPane());
        jd_Conexion.getContentPane().setLayout(jd_ConexionLayout);
        jd_ConexionLayout.setHorizontalGroup(
            jd_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_ConexionLayout.setVerticalGroup(
            jd_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_IntegracionLayout = new javax.swing.GroupLayout(jd_Integracion.getContentPane());
        jd_Integracion.getContentPane().setLayout(jd_IntegracionLayout);
        jd_IntegracionLayout.setHorizontalGroup(
            jd_IntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_IntegracionLayout.setVerticalGroup(
            jd_IntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integrador de Bases de Datos");
        setLocation(new java.awt.Point(0, 0));

        lbl_Titulo.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        lbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo.setText("<html><p style=\"text-align:center\">Integrador <br>\nde<br>\nBases de Datos</p></html>");

        mi_Integrador.setText("Integrador");
        mb_Menu.add(mi_Integrador);

        mi_Salida.setText("Salida");
        mi_Salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_SalidaMouseClicked(evt);
            }
        });
        mb_Menu.add(mi_Salida);

        setJMenuBar(mb_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_SalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_SalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mi_SalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jd_Conexion;
    private javax.swing.JDialog jd_Integracion;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JMenuBar mb_Menu;
    private javax.swing.JMenu mi_Integrador;
    private javax.swing.JMenu mi_Salida;
    // End of variables declaration//GEN-END:variables
}
